import { Deck, Flashcard } from "./types";

export const defaultDecks: Deck[] = [
  {
    id: "deck-word-01",
    name: "島風と言葉 - 八重山＆多言語名詞",
    mode: "word",
    createdAt: "2026-05-25T00:00:00Z",
    targetLanguages: ["english", "french", "chinese"],
  },
  {
    id: "deck-phrase-02",
    name: "トラベル多言語必須フレーズ",
    mode: "phrase",
    createdAt: "2026-05-25T00:01:00Z",
    targetLanguages: ["english", "french"],
  },
  {
    id: "deck-script-03",
    name: "ショートストーリー：波止場の出会い",
    mode: "script",
    createdAt: "2026-05-25T00:02:00Z",
    targetLanguages: ["english", "french", "chinese"],
  },
];

export const defaultCards: Flashcard[] = [
  // --- Deck 1: Word Mode ---
  {
    id: "card-w1",
    deckId: "deck-word-01",
    mode: "word",
    japanese: "ありがとう",
    english: "Thank you",
    french: "Merci",
    chinese: "谢谢",
    yaeyama: "にーふぁいゆー",
    photo: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    notes: "感謝の表現。八重山地域（石垣島など）では『にーふぁいゆー』、沖縄本島では『にふぇーでーびる』と言います。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },
  {
    id: "card-w2",
    deckId: "deck-word-01",
    mode: "word",
    japanese: "美しい海",
    english: "Beautiful ocean",
    french: "Belle mer",
    chinese: "美丽的海洋",
    yaeyama: "きよらさぬ海",
    photo: "https://images.unsplash.com/photo-1544735716-392fe2489ffa",
    notes: "澄み渡る碧い海。『きよらさぬ』は、清らかで洗練された美しさを表現する八重山古来の言葉です。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },
  {
    id: "card-w3",
    deckId: "deck-word-01",
    mode: "word",
    japanese: "ようこそ",
    english: "Welcome",
    french: "Bienvenue",
    chinese: "欢迎",
    yaeyama: "おーりとーり",
    photo: "https://images.unsplash.com/photo-1506929562872-bb421503ef21",
    notes: "歓迎の言葉。石垣島や竹富島を訪れると、空港や港の看板で『おーりとーり』と温かく迎えられます。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },

  // --- Deck 2: Phrase Mode ---
  {
    id: "card-p1",
    deckId: "deck-phrase-02",
    mode: "phrase",
    japanese: "お会計をお願いします。",
    english: "Check, please.",
    french: "L'addition, s'il vous plaît.",
    chinese: "请结账。",
    notes: "飲食店でのスマートな支払いフレーズ。フランス語の 'L'addition' は品よく頼むのに必須です。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },
  {
    id: "card-p2",
    deckId: "deck-phrase-02",
    mode: "phrase",
    japanese: "道に迷ってしまいました。駅はどこですか？",
    english: "I am lost. Where is the station?",
    french: "Je me suis perdu. Où est la gare ?",
    chinese: "我迷路了。请问车站在哪里？",
    notes: "緊急時の定番質問。'Je me suis perdu'（私は迷いました）から切り出すと親切に教えてもらえます。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },

  // --- Deck 3: Script Mode ---
  {
    id: "card-s1",
    deckId: "deck-script-03",
    mode: "script",
    scene: "Scene 1: 港の風のなかで",
    japanese: "あ、すみません！落とし物（帽子）ですよ！",
    english: "Oh, excuse me! You dropped your hat!",
    french: "Oh, excusez-moi ! Vous avez fait tomber votre chapeau !",
    chinese: "啊，不好意思！您的帽子掉了！",
    notes: "【話者：青年A】息を切らしながら帽子を拾って駆け寄る。ハツラツとした爽やかな表情で。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },
  {
    id: "card-s2",
    deckId: "deck-script-03",
    mode: "script",
    scene: "Scene 1: 港の風のなかで",
    japanese: "わあ、本当だ…！ありがとうございます！すごく大切にしていたんです。",
    english: "Oh, that is true...! Thank you very much! This is really precious to me.",
    french: "Ah, c'est vrai...! Merci beaucoup ! Il est très précieux pour moi.",
    chinese: "啊，真的耶…！非常感谢！这对我很珍贵。",
    notes: "【話者：女性B】ハッと振り返り、帽子を受け取る。驚きから安堵へと変わる笑顔を浮かべて。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },
  {
    id: "card-s3",
    deckId: "deck-script-03",
    mode: "script",
    scene: "Scene 2: カフェにて再会",
    japanese: "偶然ですね！さっきの港では助かりました。私、アイスコーヒーをご馳走します。",
    english: "What a coincidence! Thanks again. Let me buy you an iced coffee.",
    french: "Quelle coïncidence ! Merci encore. Laissez-moi vous offrir un café glacé.",
    chinese: "太巧了吧！刚才太谢谢你了。我请你喝杯冰咖啡吧。",
    notes: "【話者：女性B】街角のカフェテラスで偶然再会した時の、驚きつつも嬉しそうな声のトーン。",
    interval: 1,
    easyFactor: 2.5,
    repetitions: 0,
    nextReviewDate: "2026-05-25",
  },
];
